  CREATE TABLE "TCH"."TC_TID_HWSR_MAPPING" 
   (	"HWSRMAPID" NUMBER NOT NULL ENABLE, 
	"BANKCODE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"INSTITUTIONID" NUMBER NOT NULL ENABLE, 
	"MID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"TID" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"HWSRNO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MODELNAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"VENDOR" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"CLIENTID" NUMBER, 
	"HANDSHAKE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"ADDEDON" DATE, 
	"ADDEDBY" VARCHAR2(1000 BYTE), 
	"ADDIPADDRESS" VARCHAR2(100 BYTE), 
	"MODIFIEDON" DATE, 
	"MODIFIEDBY" VARCHAR2(1000 BYTE), 
	"MODIFIEDIPADDRESS" VARCHAR2(100 BYTE)
   );