ALTER TABLE TCH_PAYMENT_TXN MODIFY (P_REFERENCE_VALUE VARCHAR2(20 CHAR));
/
ALTER TABLE TCH_SETTLED_PAYMENT_TXN MODIFY (P_REFERENCE_VALUE VARCHAR2(20 CHAR));
/
ALTER TABLE TCH_SETTLED_PAYMENT_RT_VT_TT MODIFY (P_REFERENCE_VALUE VARCHAR2(20 CHAR));
/
