create or replace 
PROCEDURE TCH_AUTOSETTLEMENT_PROC
( 
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2
, O_DEBUG_POINT OUT VARCHAR2
, O_SQL_ERROR_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
)
AS 
  V_COUNT NUMBER(3):=NULL;
  V_P_ID NUMBER(10):=NULL;

  CURSOR C_PID_LIST IS
    SELECT TTP.P_ID FROM TCH_PAYMENT_TXN TTP JOIN TC_TID_HWSR_MAPPING THM ON TTP.P_TERMINAL_SERIAL_NUMBER = THM.HWSRNO
    WHERE THM.AUTOSETTLEMENT = 'Y';
  
  CURSOR C_BATCH_TERM_LIST IS
  SELECT B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER FROM TCH_BATCH_SUMMARY GROUP BY B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER;
  
BEGIN
  O_DEBUG_POINT:='1';
  
  SELECT COUNT (DISTINCT P_TERMINAL_SERIAL_NUMBER) INTO V_COUNT FROM TCH_PAYMENT_TXN;
  IF V_COUNT = 0 THEN
    O_DEBUG_POINT :='1A';
    RAISE_APPLICATION_ERROR('-21313','NO DATA FOUND FOR SETTLEMENT');
  ELSE
    BEGIN
      O_DEBUG_POINT :='1B';
  -- COPY DATA FROM PAYMENT TABLE TO SETTLEMENT TABLE
      INSERT INTO TCH_SETTLED_PAYMENT_TXN SELECT TTP.* FROM TCH_PAYMENT_TXN TTP
        JOIN TC_TID_HWSR_MAPPING THM ON TTP.P_TERMINAL_SERIAL_NUMBER = THM.HWSRNO
        WHERE THM.AUTOSETTLEMENT = 'Y' AND TTP.P_SETTLEMENT_FLAG = 'N' AND TTP.P_RESPONSE_CODE = '00' AND TTP.P_REQUEST_TYPE <> 'REVERSAL' AND TTP.P_REQUEST_TYPE <> 'TIP';    
        
      INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT SELECT TTP.* FROM TCH_PAYMENT_TXN TTP 
        JOIN TC_TID_HWSR_MAPPING THM ON TTP.P_TERMINAL_SERIAL_NUMBER = THM.HWSRNO
        WHERE THM.AUTOSETTLEMENT = 'Y' AND TTP.P_SETTLEMENT_FLAG = 'N' AND (TTP.P_RESPONSE_CODE <> '00' OR TTP.P_REQUEST_TYPE = 'REVERSAL' OR TTP.P_REQUEST_TYPE = 'TIP');
             
       FOR T IN C_PID_LIST LOOP
        UPDATE TCH_SETTLED_PAYMENT_TXN SET P_SETTLEMENT_FLAG = 'Y' WHERE P_ID = T.P_ID;
        DELETE FROM TCH_PAYMENT_TXN WHERE P_ID = T.P_ID;
       END LOOP;
       
       FOR P IN C_BATCH_TERM_LIST LOOP
        UPDATE TCH_BATCH_SUMMARY SET B_CLOSE_DATE = CURRENT_TIMESTAMP 
        WHERE B_TERMINAL_SERIAL_NUMBER = P.B_TERMINAL_SERIAL_NUMBER 
        AND B_BATCH_NUMBER = P.B_BATCH_NUMBER
        AND B_CLOSE_DATE IS NULL;
       END LOOP;
    END;
  END IF;
   O_DEBUG_POINT :='2';
  EXCEPTION
  WHEN NO_DATA_FOUND THEN
    IF O_DEBUG_POINT = '1A' THEN
      O_APP_ERROR_CODE:='A-001';
    END IF;
  WHEN OTHERS THEN
    IF O_DEBUG_POINT = '1A' THEN
      O_APP_ERROR_CODE:='A-001';
    END IF;
  O_SQL_ERROR_CODE := SQLCODE;
  
END TCH_AUTOSETTLEMENT_PROC;

/

create or replace 
PROCEDURE TCH_SETTELEMENT_PROC (
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2
--  , O_MERCHANT_ID OUT VARCHAR2
-- , O_TERMINAL_ID OUT VARCHAR2
, O_SQL_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
, O_DEBUG_POINT OUT VARCHAR2
--, O_STAN_NUMBER OUT VARCHAR2
--, O_BATCH_NUMBER OUT VARCHAR2
--, C_SETTLEMENT_DATA_REQUEST OUT SYS_REFCURSOR
--, C_SETTLEMENT_DATA_TRANSACTIONS OUT SYS_REFCURSOR
--, C_SETTLEMENT_DATA_PREAUTH OUT SYS_REFCURSOR
, C_HEALTH_OBJECT OUT SYS_REFCURSOR
)AS 

V_COUNT NUMBER(4):=NULL;
V_MID VARCHAR2(20):=NULL;
V_TID VARCHAR2(15):=NULL;

CURSOR C_PID_LIST IS
  SELECT P_ID FROM TCH_PAYMENT_TXN WHERE P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
  
CURSOR C_BATCH_TERM_LIST IS
  SELECT B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER FROM TCH_BATCH_SUMMARY GROUP BY B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER;
  
BEGIN

-- GET SETTLEMENT RELATED DATA
    O_DEBUG_POINT:='1';
    SELECT COUNT(1) INTO V_COUNT FROM TCH_PAYMENT_TXN TTP JOIN TCH_HANDSHAKES TH ON TTP.P_MERCHANTID = TH.H_CARD_ACQUIRING_ID
				AND TTP.P_TERMINALID = TH.H_TID AND TTP.P_CLIENTID = TH.H_CLIENT_ID
				WHERE TTP.P_SETTLEMENT_FLAG = 'N'
				AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
    IF V_COUNT = 0 THEN
      O_DEBUG_POINT:='1A';
      RAISE_APPLICATION_ERROR(-20121,'NO DATA FOUND FOR SETTELEMENT');
    ELSE
     BEGIN
        O_DEBUG_POINT:='1B';
        -- MOVE THE TRANSACTION FROM TCH PAYMENT TO TCH SETTLEMENT 
        INSERT INTO TCH_SETTLED_PAYMENT_TXN SELECT * FROM TCH_PAYMENT_TXN TTP 
        WHERE TTP.P_SETTLEMENT_FLAG = 'N' AND TTP.P_RESPONSE_CODE = '00' AND TTP.P_REQUEST_TYPE <> 'REVERSAL' AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;    
        
        INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT SELECT * FROM TCH_PAYMENT_TXN TTP 
        WHERE TTP.P_SETTLEMENT_FLAG = 'N' AND (TTP.P_RESPONSE_CODE <> '00' OR TTP.P_REQUEST_TYPE = 'REVERSAL') AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
        
         FOR T IN C_PID_LIST LOOP
          UPDATE TCH_SETTLED_PAYMENT_TXN SET P_SETTLEMENT_FLAG = 'Y' WHERE P_ID = T.P_ID;
          DELETE FROM TCH_PAYMENT_TXN WHERE P_ID = T.P_ID;
         END LOOP;
         
         FOR P IN C_BATCH_TERM_LIST LOOP
          UPDATE TCH_BATCH_SUMMARY SET B_CLOSE_DATE = CURRENT_TIMESTAMP 
          WHERE B_TERMINAL_SERIAL_NUMBER = P.B_TERMINAL_SERIAL_NUMBER 
          AND B_BATCH_NUMBER = P.B_BATCH_NUMBER
          AND B_CLOSE_DATE IS NULL;
         END LOOP;
         COMMIT;
      END;
     END IF; 
     
   
--GET BATCH NUMBER
--  O_DEBUG_POINT:='2';
--    
--    SELECT COUNT(1) INTO V_COUNT  FROM TCH_PAYMENT_TXN TTP JOIN TCH_HANDSHAKES TH 
--        ON TTP.P_MERCHANTID = TH.H_CARD_ACQUIRING_ID AND TTP.P_TERMINALID = TH.H_TID AND TTP.P_CLIENTID = TH.H_CLIENT_ID
--				WHERE TTP.P_SETTLEMENT_FLAG = 'N' AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
--             
--    IF V_COUNT <> 0 THEN
--      BEGIN
--        O_DEBUG_POINT:='2A';
---- GET MID AND TID, BATCH NUMBER
--        SELECT DISTINCT TTP.P_MERCHANTID, TTP.P_TERMINALID INTO V_MID, V_TID  FROM TCH_PAYMENT_TXN TTP JOIN TCH_HANDSHAKES TH 
--        ON TTP.P_MERCHANTID = TH.H_CARD_ACQUIRING_ID AND TTP.P_TERMINALID = TH.H_TID AND TTP.P_CLIENTID = TH.H_CLIENT_ID
--				WHERE TTP.P_RESPONSE_CODE='00' AND TTP.P_SETTLEMENT_FLAG = 'N' AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
--     END;
--    ELSE
--      BEGIN 
--        O_DEBUG_POINT:='2B';
--        RAISE_APPLICATION_ERROR(-20121,'NO DATA FOUND');
--      END;
--    END IF;
  

-- GET HEALTH OBJECT DETAILS
  O_DEBUG_POINT:='3AA';
    OPEN C_HEALTH_OBJECT FOR 
      SELECT * FROM TCH_HEALTH_OBJECT WHERE TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
      AND TID = V_TID AND MID = V_MID;
      
  O_DEBUG_POINT:='4';
  
   EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        IF O_DEBUG_POINT = '1A' THEN 
            O_APP_ERROR_CODE := 'S-888';
        ELSIF O_DEBUG_POINT = '3AA' THEN 
            O_APP_ERROR_CODE := 'SH-88';
        ELSIF O_DEBUG_POINT = '2B' THEN 
            O_APP_ERROR_CODE := 'S-888';
        END IF;
    WHEN OTHERS THEN
        IF O_DEBUG_POINT = '1A' THEN 
            O_APP_ERROR_CODE := 'S-888'; 
        ELSIF O_DEBUG_POINT = '3AA' THEN 
            O_APP_ERROR_CODE := 'SH-88';
        ELSIF O_DEBUG_POINT = '2B' THEN 
            O_APP_ERROR_CODE := 'S-888';
        END IF;
        
      O_SQL_CODE := SQLCODE;
    
END TCH_SETTELEMENT_PROC;