create or replace 
FUNCTION TCH_BIN_VALIDATION 
(
  BINVAL IN VARCHAR2,  
  TERM_SERIAL_NUMBER IN VARCHAR2
) 
RETURN VARCHAR2 
AS 
V_PRESENT VARCHAR2(20):=NULL;
V_BIN VARCHAR2(6):=NULL;
V_BIN_LIMIT VARCHAR2(2):=NULL;
BEGIN
dbms_output.put_line('BINVAL ' || BINVAL);
  SELECT AC_VALUE INTO V_BIN_LIMIT FROM TCH_APPL_CONFIG WHERE AC_NAME = 'BIN';
  V_BIN:=SUBSTR(BINVAL,0,TO_NUMBER(V_BIN_LIMIT));
  
    FOR I IN 
      (
      SELECT BIN_RANGE_HIGH,BIN_RANGE_LOW,PIN_BYPASS_FLAG,SCHEME_CODE FROM TCH_JCBUPI_BIN
      ) 
      LOOP
        IF TO_NUMBER(I.BIN_RANGE_HIGH) >= TO_NUMBER(V_BIN) AND TO_NUMBER(I.BIN_RANGE_LOW) <= TO_NUMBER(V_BIN) THEN
          BEGIN
           V_PRESENT := 'T2-'||I.PIN_BYPASS_FLAG||'-'||I.SCHEME_CODE;
          END;
        END IF;
      END LOOP;
      
    FOR I IN 
      (
        SELECT TERMPARAMID,CARD_RANGE_HIGH,CARD_RANGE_LOW FROM TC_TID_HWSR_MAPPING THM JOIN TC_TERM_PARAMETER TTP ON THM.MID = TTP.MID AND TTP.TID = THM.TID
        WHERE THM.HWSRNO = TERM_SERIAL_NUMBER
      ) 
      LOOP
      IF TO_NUMBER(I.CARD_RANGE_HIGH) >= TO_NUMBER(V_BIN) AND TO_NUMBER(I.CARD_RANGE_LOW) <= TO_NUMBER(V_BIN) THEN
        BEGIN
        -- BIN VALUE PRESENT IN TERM_PARAMETER TABLE
        V_PRESENT := 'T1-'||I.TERMPARAMID;
        END;
      END IF;
    END LOOP;
  dbms_output.put_line('V_PRESENT ' || V_PRESENT);
  RETURN V_PRESENT;
END TCH_BIN_VALIDATION;

/