DROP TABLE "TCH_UTILITY_INFO" cascade constraints;
--------------------------------------------------------
--  DDL for Table TCH_UTILITY_INFO
--------------------------------------------------------

  CREATE TABLE "TCH_UTILITY_INFO" 
   (	"U_ID" NUMBER, 
	"U_IP_ADDRESS" VARCHAR2(20 BYTE), 
	"U_PORT_NUMBER" VARCHAR2(4 BYTE), 
	"U_URL" VARCHAR2(50 BYTE), 
	"U_CREATED" DATE, 
	"U_APP_NAME" VARCHAR2(20 BYTE), 
	"U_UPDATED" DATE, 
	"ADDED_BY" VARCHAR2(50 BYTE), 
	"U_PRINT_LABELS" VARCHAR2(600 BYTE), 
	"U_ONE_TIME_LBL" VARCHAR2(50 BYTE), 
	"U_LBL_VAL" VARCHAR2(3 BYTE)
   );
   /
   
ALTER TABLE "TCH_UTILITY_INFO" ADD CONSTRAINT "TCH_UTILITY_INFO_PK" PRIMARY KEY ("U_ID")
/
ALTER TABLE "TCH"."TCH_UTILITY_INFO" MODIFY ("U_ID" NOT NULL ENABLE);
/
Insert into TCH_UTILITY_INFO (U_ID,U_IP_ADDRESS,U_PORT_NUMBER,U_URL,U_CREATED,U_APP_NAME,U_UPDATED,ADDED_BY,U_PRINT_LABELS,U_ONE_TIME_LBL,U_LBL_VAL) values (2,'0','0','http://164.100.137.245:8080/egras',null,'EGRAS',null,null,'AAB BRANCH CODE:,GRN ID :','ENTER OTP :','5');
Insert into TCH_UTILITY_INFO (U_ID,U_IP_ADDRESS,U_PORT_NUMBER,U_URL,U_CREATED,U_APP_NAME,U_UPDATED,ADDED_BY,U_PRINT_LABELS,U_ONE_TIME_LBL,U_LBL_VAL) values (1,'0','0','http://182.75.43.245/APIPay/PlaceMyOrder.asmx',null,'AAB',to_date('17-JAN-17','DD-MON-RR'),'Pooja','AAB BRANCH CODE:,AAB TRNS ID :','ENTER TRSNID :','6');
/

CREATE UNIQUE INDEX "TCH_UTILITY_INFO_PK" ON "TCH_UTILITY_INFO" ("U_ID");
/

