
--------------------------------------------------------
--  DDL for Table TCH_AXISEPAY_REPORT
--------------------------------------------------------

 CREATE TABLE TCH_AXISEPAY_REPORT
   (	
    A_MID VARCHAR2(20 BYTE), 
    A_TID VARCHAR2(15 BYTE),
    A_URN VARCHAR2(20 BYTE), 
    A_RRN VARCHAR2(20 BYTE), 
    A_CID VARCHAR2(20 BYTE),
    A_RID VARCHAR2(20 BYTE),
    A_AMOUNT VARCHAR2(20 BYTE),
    A_TRASACTIONDATE VARCHAR2(25 BYTE), 
    A_CUSTNAME VARCHAR2(200 BYTE), 
    A_CRN VARCHAR2(20 BYTE), 
    A_STATUS VARCHAR2(20 BYTE), 
    A_ERRORCODE VARCHAR2(20 BYTE), 
    A_ERRORDESC VARCHAR2(100 BYTE), 
    A_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 CONSTRAINT "TCH_AXISEPAY_REPORT_PK" PRIMARY KEY ("A_URN"));