  CREATE TABLE "TCH"."TCH_ROLES" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP ENABLE, 
	 CONSTRAINT "PK_ROLES_ID" PRIMARY KEY ("ID")
   );