CREATE TABLE "TCH"."TCH_USERS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ENABLED" NUMBER(10,0) NOT NULL ENABLE, 
	"ACCOUNTNOTEXPIRED" NUMBER(10,0) NOT NULL ENABLE, 
	"CREDENTIALNOTEXPIRED" NUMBER(10,0) NOT NULL ENABLE, 
	"ACCOUNTNOTLOCKED" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	"UPDATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 CONSTRAINT "PK_USER_ID" PRIMARY KEY ("ID")
   ) ;