create or replace 
PROCEDURE TCH_DETAIL_REPORT_PROC1 (
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2
, I_TID IN VARCHAR2
, I_MID IN VARCHAR2
, I_HOST_ID IN VARCHAR2
, I_OFFSET IN VARCHAR2
, I_DES_PARAM IN VARCHAR2
, O_BATCH_NUMBER OUT VARCHAR2
, O_SQL_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
, O_DEBUG_POINT OUT VARCHAR2
, O_TOTAL_COUNT OUT VARCHAR2
, O_FINAL_COUNT OUT VARCHAR2
, C_DETAIL_REPORT_DATA OUT SYS_REFCURSOR
, C_DETAIL_REPORT_TABLE_DATA OUT SYS_REFCURSOR
)
AS 
V_NORMAL_COUNT VARCHAR2(20):=NULL;
V_AMEX_COUNT VARCHAR2(20):=NULL;
V_DCC_COUNT VARCHAR2(20):=NULL;
V_WLT_COUNT VARCHAR2(20):=NULL;

BEGIN

-- CHECK ERROR CONIDTION TO BE SEND OR NOT BASED ON THE COUNT FROM EACH TABLE
    O_DEBUG_POINT :='1';
    SELECT SUM(TOTAL_VAL) INTO O_FINAL_COUNT FROM 
    (
      SELECT COUNT(1) AS TOTAL_VAL  FROM TCH_PAYMENT_TXN 
      WHERE P_RESPONSE_CODE = '00' 
      AND P_REQUEST_TYPE <> 'TIP'
      AND P_REQUEST_TYPE <> 'REVERSAL' 
      AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
      AND P_TERMINALID = I_TID
      
      UNION ALL
      
      SELECT COUNT(1) AS TOTAL_VAL  FROM TCH_PAYMENT_AMEX_TXN 
      WHERE P_RESPONSE_CODE = '00' 
      AND P_REQUEST_TYPE <> 'TIP'
      AND P_REQUEST_TYPE <> 'REVERSAL' 
      AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
      AND P_TERMINALID = I_TID
      
      
      UNION ALL
      
      SELECT COUNT(1) AS TOTAL_VAL  FROM TCH_WALLET_TXN 
      WHERE W_RESPONSE_CODE = '00' 
      AND W_REQUEST_TYPE <> 'REVERSAL' 
      AND W_ISCOMPLETED= 'Y'
      AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER
      AND W_TID = I_TID
      UNION ALL
      
      SELECT COUNT(1) AS TOTAL_VAL  FROM TCH_DCC_PAYMENT_TXN 
      WHERE P_RESPONSE_CODE = '00' 
      AND P_REQUEST_TYPE <> 'TIP'
      AND P_REQUEST_TYPE <> 'REVERSAL' 
      AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
      AND P_TERMINALID = I_TID
    );
    
    IF O_FINAL_COUNT <> 0 THEN
      IF I_HOST_ID IS NULL THEN
        BEGIN
            O_DEBUG_POINT :='1A';
            SELECT COUNT(1),COUNT(1),P_BATCH_NUMBER INTO V_NORMAL_COUNT,O_TOTAL_COUNT,O_BATCH_NUMBER FROM TCH_PAYMENT_TXN 
              WHERE P_RESPONSE_CODE = '00' 
              AND P_REQUEST_TYPE <> 'TIP'
              AND P_REQUEST_TYPE <> 'REVERSAL'
              AND P_TERMINALID = I_TID
              AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
              GROUP BY P_BATCH_NUMBER;
              
          EXCEPTION
            WHEN NO_DATA_FOUND THEN
              O_TOTAL_COUNT:='0';
              V_NORMAL_COUNT:='0';
        END;    
        
         BEGIN
          O_DEBUG_POINT :='1I';
          SELECT COUNT(1),COUNT(1),W_BATCH_NUMBER INTO V_WLT_COUNT,O_TOTAL_COUNT,O_BATCH_NUMBER FROM TCH_WALLET_TXN 
              WHERE W_RESPONSE_CODE = '00' 
              AND W_REQUEST_TYPE <> 'REVERSAL' 
              AND W_ISCOMPLETED = 'Y'
              AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER
              AND W_TID = I_TID
              GROUP BY W_BATCH_NUMBER;
              
          EXCEPTION
            WHEN NO_DATA_FOUND THEN
              O_TOTAL_COUNT:='0';
              V_WLT_COUNT:='0';
        END;
      ELSIF I_HOST_ID = 'AMEX' THEN
        BEGIN
          O_DEBUG_POINT :='1B';
          SELECT COUNT(1),COUNT(1),P_BATCH_NUMBER INTO V_AMEX_COUNT,O_TOTAL_COUNT,O_BATCH_NUMBER FROM TCH_PAYMENT_AMEX_TXN 
              WHERE P_RESPONSE_CODE = '00' 
              AND P_REQUEST_TYPE <> 'TIP'
              AND P_REQUEST_TYPE <> 'REVERSAL'
              AND P_TERMINALID = I_TID
              AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
              GROUP BY P_BATCH_NUMBER;
              
         EXCEPTION
            WHEN NO_DATA_FOUND THEN
              O_TOTAL_COUNT:='0';
              V_AMEX_COUNT:='0';
        END;
        
                
      ELSIF I_HOST_ID = 'DCC' THEN
        BEGIN
          O_DEBUG_POINT :='1C';
          SELECT COUNT(1),COUNT(1),P_BATCH_NUMBER INTO V_DCC_COUNT,O_TOTAL_COUNT,O_BATCH_NUMBER FROM TCH_DCC_PAYMENT_TXN 
              WHERE P_RESPONSE_CODE = '00' 
              AND P_REQUEST_TYPE <> 'TIP'
              AND P_REQUEST_TYPE <> 'REVERSAL'
              AND P_TERMINALID = I_TID
              AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
              GROUP BY P_BATCH_NUMBER;
              
          EXCEPTION
            WHEN NO_DATA_FOUND THEN
              O_TOTAL_COUNT:='0';
              V_DCC_COUNT:='0';
        END;
      END IF;
    ELSE
      O_DEBUG_POINT :='1D';
      O_FINAL_COUNT:= 0;
      RAISE_APPLICATION_ERROR('-20555','NO MAPPING FOUND');
    END IF;
    
    --OFFSET I_OFFSET ROWS FETCH NEXT 10 ROWS ONLY;
    IF I_DES_PARAM <> 1 THEN 
      IF O_TOTAL_COUNT >= 200 THEN
        O_DEBUG_POINT := '1BA';
        RAISE_APPLICATION_ERROR('-21212','NO OF RECORDS MORE THAN 100');
      END IF;
    END IF;
    
--CHECK CONDITION FOR COUNTINUTY FLAG
  IF O_TOTAL_COUNT <> 0 THEN
    O_TOTAL_COUNT := O_TOTAL_COUNT - I_OFFSET;
    IF O_TOTAL_COUNT < 10 THEN
      O_TOTAL_COUNT := '0';
    ELSE
      O_TOTAL_COUNT := '1';
    END IF;
  END IF;
  
-- GET DETAIL REPORT DATA FROM PAYMENT TABLE IN THE PACKET OF 10
  
  IF I_HOST_ID IS NULL AND V_NORMAL_COUNT <> '0' THEN
    BEGIN 
    O_DEBUG_POINT:='1E';
     OPEN C_DETAIL_REPORT_DATA FOR
      SELECT P_REQUEST_TYPE , P_INVOICENUMBER, P_AUTH_ID, P_LAST_FOUR_DIGIT, 
      P_EXPIRYDATE, P_ORIGINAL_AMOUNT, P_CARD_LABEL, P_TIP_APPROVED FROM
      
      ( SELECT P_REQUEST_TYPE , P_INVOICENUMBER, P_AUTH_ID, P_LAST_FOUR_DIGIT, 
      P_EXPIRYDATE, P_ORIGINAL_AMOUNT, P_CARD_LABEL, P_TIP_APPROVED
      FROM TCH_PAYMENT_TXN WHERE P_RESPONSE_CODE = '00' 
      AND P_REQUEST_TYPE <> 'TIP'
      AND P_REQUEST_TYPE <> 'REVERSAL'
      AND P_TERMINALID = I_TID
      AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER 
          
      UNION ALL
      
      SELECT W_REQUEST_TYPE AS P_REQUEST_TYPE , W_INV_NUMBER AS P_INVOICENUMBER,'' 
      AS P_AUTH_ID, W_WALLET_ID AS P_LAST_FOUR_DIGIT, '' as P_EXPIRYDATE,
      W_TXN_AMOUNT AS P_ORIGINAL_AMOUNT, W_WALLET_TYPE AS P_CARD_LABEL, '' as P_TIP_APPROVED
      FROM TCH_WALLET_TXN WHERE W_RESPONSE_CODE = '00' 
      AND W_ISCOMPLETED = 'Y'
      AND W_REQUEST_TYPE <> 'REVERSAL' 
      AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER
      AND W_TID = I_TID 
      ) ORDER BY P_INVOICENUMBER OFFSET I_OFFSET ROWS FETCH NEXT 20 ROWS ONLY;
      
    END;
  ELSIF I_HOST_ID = 'AMEX' AND V_AMEX_COUNT <> '0' THEN
    BEGIN
      O_DEBUG_POINT:='1F';
     OPEN C_DETAIL_REPORT_DATA FOR
      SELECT P_REQUEST_TYPE , P_INVOICENUMBER, P_AUTH_ID, P_LAST_FOUR_DIGIT, 
      P_EXPIRYDATE, P_ORIGINAL_AMOUNT, P_CARD_LABEL, P_TIP_APPROVED
      FROM TCH_PAYMENT_AMEX_TXN WHERE P_RESPONSE_CODE = '00' 
      AND P_REQUEST_TYPE <> 'TIP'
      AND P_REQUEST_TYPE <> 'REVERSAL'
      AND P_TERMINALID = I_TID
      AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER ORDER BY P_INVOICENUMBER
      OFFSET I_OFFSET ROWS FETCH NEXT 20 ROWS ONLY;
    END;
    
     ELSIF I_HOST_ID = 'WLT' AND V_WLT_COUNT <> '0' THEN
    BEGIN
      O_DEBUG_POINT:='1J';
     OPEN C_DETAIL_REPORT_DATA FOR
        SELECT W_REQUEST_TYPE AS P_REQUEST_TYPE , W_INV_NUMBER AS P_INVOICENUMBER,'' 
      AS P_AUTH_ID, W_WALLET_ID AS P_LAST_FOUR_DIGIT, '' as P_EXPIRYDATE,
      W_TXN_AMOUNT AS P_ORIGINAL_AMOUNT, W_WALLET_TYPE AS P_CARD_LABEL, '' as P_TIP_APPROVED
      FROM TCH_WALLET_TXN WHERE W_RESPONSE_CODE = '00' 
      AND W_ISCOMPLETED = 'Y'
      AND W_REQUEST_TYPE <> 'REVERSAL' 
      AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER
      AND W_TID = I_TID ORDER BY P_INVOICENUMBER
      OFFSET I_OFFSET ROWS FETCH NEXT 20 ROWS ONLY;
    END;
    
  ELSIF I_HOST_ID = 'DCC' AND V_DCC_COUNT <> '0' THEN
   BEGIN
      O_DEBUG_POINT:='1G';
     OPEN C_DETAIL_REPORT_DATA FOR
      SELECT P_REQUEST_TYPE , P_INVOICENUMBER, P_AUTH_ID, P_LAST_FOUR_DIGIT, 
      P_EXPIRYDATE, P_ORIGINAL_AMOUNT, P_CARD_LABEL, P_TIP_APPROVED
      FROM TCH_DCC_PAYMENT_TXN WHERE P_RESPONSE_CODE = '00' 
      AND P_REQUEST_TYPE <> 'TIP'
      AND P_REQUEST_TYPE <> 'REVERSAL'
      AND P_TERMINALID = I_TID
      AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER ORDER BY P_INVOICENUMBER
      OFFSET I_OFFSET ROWS FETCH NEXT 20 ROWS ONLY;
    END;
  END IF;
  O_DEBUG_POINT:='1H';
-- GET DETAIL TABLE INFORMATION
  OPEN C_DETAIL_REPORT_TABLE_DATA FOR
    SELECT D_DISPLAY_MSG_PARAM,D_COLUMN_NAME FROM TCH_DETAIL_REPORT ORDER BY D_DISPLAY_SEQ_NUMBER;
    
  O_BATCH_NUMBER := LPAD(O_BATCH_NUMBER,6,'0');
  O_DEBUG_POINT := '2';
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      IF O_DEBUG_POINT = '1D' THEN
        O_APP_ERROR_CODE :='D-402';
      END IF;
    WHEN OTHERS THEN
      IF O_DEBUG_POINT = '1BA' THEN
        O_APP_ERROR_CODE :='D-403';
     ELSIF O_DEBUG_POINT = '1D' THEN
        O_APP_ERROR_CODE :='D-402';
      END IF;
  O_SQL_CODE := SQLCODE;
END TCH_DETAIL_REPORT_PROC1;