create or replace 
PROCEDURE TCH_SETTELEMENT_PROC1 (
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2
, O_SQL_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
, O_DEBUG_POINT OUT VARCHAR2
, C_HEALTH_OBJECT OUT SYS_REFCURSOR
)AS 
TYPE TCH_STRING_ARRAY IS VARRAY (5000000) OF VARCHAR2(30);
V_CRDB_PID TCH_STRING_ARRAY;
V_TID_NORMAL TCH_STRING_ARRAY;
V_COUNT NUMBER(4):=NULL;
V_MID VARCHAR2(20):=NULL;
V_TID VARCHAR2(15):=NULL;

  
CURSOR C_BATCH_TERM_LIST IS
  SELECT B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER
      FROM TCH_BATCH_SUMMARY TBS JOIN TC_TID_HWSR_MAPPING THM ON TBS.B_TERMINAL_SERIAL_NUMBER = THM.HWSRNO
      WHERE TBS.B_CLOSE_DATE IS NULL
      GROUP BY B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER;

BEGIN

-- GET SETTLEMENT RELATED DATA
    O_DEBUG_POINT:='1';
    SELECT SUM(TOTAL_VAL) INTO V_COUNT FROM 
    (
      SELECT COUNT(1) AS TOTAL_VAL  FROM TCH_PAYMENT_TXN TTP
      WHERE TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
        AND TTP.P_RESPONSE_CODE = '00' 
        AND TTP.P_REQUEST_TYPE <> 'REVERSAL' 
        AND TTP.P_REQUEST_TYPE <> 'TIP' 
        AND TTP.P_REQUEST_TYPE <> 'VOIDREFUND'
        AND TTP.P_REQUEST_TYPE <> 'VOIDEMISALE'
        AND TTP.P_REQUEST_TYPE <> 'VOIDSCHBK'
        AND TTP.P_REQUEST_TYPE <> 'VOIDSALETIP'
        AND TTP.P_REQUEST_TYPE <> 'VOID'
    );
    
    IF V_COUNT = 0 THEN
      O_DEBUG_POINT:='1A';
     
--  COPY REJECTED DATA FROM PAYMENT TABLE TO SETTLEMENT TABLE          
      INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT SELECT TTP.* FROM TCH_PAYMENT_TXN TTP 
        WHERE (TTP.P_RESPONSE_CODE <> '00' 
              OR TTP.P_REQUEST_TYPE = 'REVERSAL' 
              OR TTP.P_REQUEST_TYPE = 'TIP' 
              OR TTP.P_REQUEST_TYPE = 'VOID'
              OR TTP.P_REQUEST_TYPE = 'VOIDREFUND'
              OR TTP.P_REQUEST_TYPE = 'VOIDEMISALE'
              OR TTP.P_REQUEST_TYPE = 'VOIDSCHBK'
              OR TTP.P_REQUEST_TYPE = 'VOIDSALETIP')
              AND  TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
              
      DELETE FROM TCH_PAYMENT_TXN  
        WHERE ( P_RESPONSE_CODE <> '00' 
          OR P_REQUEST_TYPE = 'REVERSAL' 
          OR P_REQUEST_TYPE = 'TIP' 
          OR P_REQUEST_TYPE = 'VOID'
          OR P_REQUEST_TYPE = 'VOIDREFUND'
          OR P_REQUEST_TYPE = 'VOIDEMISALE'
          OR P_REQUEST_TYPE = 'VOIDSCHBK'
          OR P_REQUEST_TYPE = 'VOIDSALETIP')
          AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
      RAISE_APPLICATION_ERROR(-20121,'NO DATA FOUND FOR SETTELEMENT');
    ELSE
     BEGIN
        O_DEBUG_POINT:='1B';
        SELECT P_ID,P_TERMINALID BULK COLLECT INTO V_CRDB_PID,V_TID_NORMAL FROM TCH_PAYMENT_TXN
        WHERE P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
        -- MOVE THE TRANSACTION FROM TCH PAYMENT TO TCH SETTLEMENT 
        INSERT INTO TCH_SETTLED_PAYMENT_TXN SELECT TTP.* FROM TCH_PAYMENT_TXN TTP
        WHERE TTP.P_RESPONSE_CODE = '00' 
        AND TTP.P_REQUEST_TYPE <> 'REVERSAL' 
        AND TTP.P_REQUEST_TYPE <> 'TIP' 
        AND TTP.P_REQUEST_TYPE <> 'VOIDREFUND'
        AND TTP.P_REQUEST_TYPE <> 'VOIDSCHBK'
        AND TTP.P_REQUEST_TYPE <> 'VOIDSALETIP'
        AND TTP.P_REQUEST_TYPE <> 'VOIDEMISALE'
        AND TTP.P_REQUEST_TYPE <> 'VOID'
        AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;       
        --END OF MOVE THE TRANSACTION FROM TCH PAYMENT TO TCH SETTLEMENT
        
 --COPY REJECTED DATA FROM PAYMENT TABLE TO SETTLEMENT TABLE  
      INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT SELECT TTP.* FROM TCH_PAYMENT_TXN TTP 
        WHERE (TTP.P_RESPONSE_CODE <> '00' 
              OR TTP.P_REQUEST_TYPE = 'REVERSAL' 
              OR TTP.P_REQUEST_TYPE = 'TIP' 
              OR TTP.P_REQUEST_TYPE = 'VOID'
              OR TTP.P_REQUEST_TYPE = 'VOIDREFUND'
              OR TTP.P_REQUEST_TYPE = 'VOIDSALETIP'
              OR TTP.P_REQUEST_TYPE = 'VOIDEMISALE'
              OR TTP.P_REQUEST_TYPE = 'VOIDSCHBK')
              AND TTP.P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
        O_DEBUG_POINT :='1BC';

         FOR INDX IN V_CRDB_PID.FIRST..V_CRDB_PID.LAST LOOP
          DELETE FROM TCH_PAYMENT_TXN WHERE P_ID = V_CRDB_PID(INDX) 
          AND P_TERMINALID = V_TID_NORMAL(INDX)
          AND P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER;
        END LOOP;
        
         FOR P IN C_BATCH_TERM_LIST LOOP
          UPDATE TCH_BATCH_SUMMARY SET B_CLOSE_DATE = CURRENT_TIMESTAMP 
          WHERE B_TERMINAL_SERIAL_NUMBER = P.B_TERMINAL_SERIAL_NUMBER 
          AND B_BATCH_NUMBER = P.B_BATCH_NUMBER
          AND B_CLOSE_DATE IS NULL;
         END LOOP;
         COMMIT;
      END;
     END IF; 
     
     
     TCH_SETTELEMENT_WALLET_PROC( I_TERMINAL_SERIAL_NUMBER, O_SQL_CODE, O_APP_ERROR_CODE,O_DEBUG_POINT );
     
-- GET HEALTH OBJECT DETAILS
  O_DEBUG_POINT:='3AA';
    OPEN C_HEALTH_OBJECT FOR 
      SELECT * FROM TCH_HEALTH_OBJECT WHERE TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
      AND TID = V_TID AND MID = V_MID;
  O_DEBUG_POINT:='4';
  
   EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        IF O_DEBUG_POINT = '1A' THEN 
            O_APP_ERROR_CODE := 'S-888';
        ELSIF O_DEBUG_POINT = '3AA' THEN 
            O_APP_ERROR_CODE := 'SH-88';
        END IF;
    WHEN OTHERS THEN
        IF O_DEBUG_POINT = '1A' THEN 
            O_APP_ERROR_CODE := 'S-888'; 
        ELSIF O_DEBUG_POINT = '3AA' THEN 
            O_APP_ERROR_CODE := 'SH-88';
        END IF;
        
      O_SQL_CODE := SQLCODE;
    
END TCH_SETTELEMENT_PROC1;