CREATE TABLE "TCH_LOGS" 
(	
    "ID" NUMBER(10,0) NOT NULL ENABLE, 
    "REQUEST_TYPE" VARCHAR2(30 CHAR),
	"REQUEST" CLOB, 
	"RESPONSE" CLOB, 
	"REQUEST_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"RESPONSE_TIME" TIMESTAMP (6), 
    "PROCESSING_TIME" NUMBER(10,0),
	"STATUS" CHAR(1), 
	 PRIMARY KEY ("ID")
);