 CREATE TABLE "TCH"."TCH_FUNCTIONGROUPS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6)  DEFAULT CURRENT_TIMESTAMP ENABLE, 
	 CONSTRAINT "PK_FUNCTIONGROUPS_ID" PRIMARY KEY ("ID")
   );