
  CREATE TABLE "TCH_MENU_OBJECT" 
   (	"TMO_ID" NUMBER, 
	"TMO_MENU_NAME" VARCHAR2(40 BYTE), 
	"TMO_PARENT_KEY" NUMBER, 
	"TMO_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TMO_UPDATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TMO_MENU_FLAG" VARCHAR2(10 BYTE), 
	"TMO_HEADER_NAME" VARCHAR2(40 BYTE), 
	"TMO_VALUE" VARCHAR2(5 BYTE), 
	 CONSTRAINT "TCH_MENU_OBJECT_PK" PRIMARY KEY ("TMO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TCHSIT"  ENABLE, 
	 CONSTRAINT "TCH_MENU_OBJECT_FK1" FOREIGN KEY ("TMO_PARENT_KEY")
	  REFERENCES "TCH_SIT"."TCH_MENU_OBJECT" ("TMO_ID") ON DELETE CASCADE ENABLE
   )  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TCH_MENU_OBJECT_TRG" 
BEFORE INSERT ON TCH_MENU_OBJECT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TMO_ID IS NULL THEN
      SELECT SEQ_TC_MENUOBJECT_ID.NEXTVAL INTO :NEW.TMO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TCH_MENU_OBJECT_TRG" ENABLE;

-- WALLET 
INSERT INTO TCH_MENU_OBJECT VALUES (11,'WALLET',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'WALLET','SELECT PAYMENT MODE',1);
INSERT INTO TCH_MENU_OBJECT VALUES (12,'FREECHARGE',11,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FREECHARGE','SELECT WALLET',11);

INSERT INTO TCH_MENU_OBJECT VALUES (13,'WALLET',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'WALLET','SELECT PAYMENT MODE',2);
INSERT INTO TCH_MENU_OBJECT VALUES (14,'FREECHARGE',13,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FREECHARGE','SELECT WALLET',13);



