create or replace 
PROCEDURE TCH_AUTOSETTLEMENT_WALLET_PROC
( 
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2 
, O_DEBUG_POINT OUT VARCHAR2
, O_SQL_ERROR_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
)AS 
TYPE TCH_STRING_ARRAY IS VARRAY (5000000) OF VARCHAR2(30);
V_WALLET_PID TCH_STRING_ARRAY;
V_WALLET_TID TCH_STRING_ARRAY;
V_COUNT VARCHAR2(30):=NULL;

BEGIN
  O_DEBUG_POINT:='1W';
-- GET ALL PID IN ARRAY
    SELECT W_TXN_REF_ID,W_TID BULK COLLECT INTO V_WALLET_PID,V_WALLET_TID FROM TCH_WALLET_TXN;
    
    V_COUNT := V_WALLET_PID.COUNT;
    
     IF V_COUNT = 0 THEN
    O_DEBUG_POINT :='2W';
    RAISE_APPLICATION_ERROR(-20313,'NO DATA FOUND FOR SETTLEMENT');
  ELSE
    BEGIN
      O_DEBUG_POINT :='3W';

  INSERT INTO TCH_SETTLED_PAYMENT_TXN (P_ID, P_PANNUMBER, P_ORIGINAL_AMOUNT, P_CARD_ENTRYMODE, P_MERCHANTID, P_TERMINALID,
  P_INVOICENUMBER, P_TERMINAL_SERIAL_NUMBER, P_DATE, P_REFERENCE_VALUE, P_BATCH_NUMBER, P_REQUEST_TYPE, P_RESPONSE_CODE,  
  P_RETRIVAL_REF_NUMBER, P_STAN_NUMBER, P_CREATED, P_UPDATED, P_SETTLEMENT_FLAG, 
  P_PROCESSING_CODE, P_MTI, P_TXN_CHANNEL, P_APP_NAME, P_EXTRA_INFO,P_CARD_LABEL,P_REFUND_APPROVED,P_CURRENCY_CODE ) 
    SELECT SEQ_TC_WALLET_SETTLEMENT_ID.NEXTVAL, '405663' || W_WALLET_ID, W_TXN_AMOUNT, '010', W_MID, W_TID, W_INV_NUMBER, W_TERM_SER_NUM, W_TXN_DATENTIME,
 W_TXN_ID,  W_BATCH_NUMBER, W_REQUEST_TYPE, W_RESPONSE_CODE, W_TXN_REF_ID, '000001', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,
 'Y', CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '000000' WHEN 'REFUND' THEN '200000' END,
 CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '200' WHEN 'REFUND' THEN '220' END,'F',
 W_WALLET_TYPE, W_TXN_ID,W_WALLET_TYPE,W_REFUND_APPROVED,'356' FROM TCH_WALLET_TXN WHERE W_RESPONSE_CODE='00' AND 
 (W_REQUEST_TYPE = 'SALE' OR W_REQUEST_TYPE='REFUND') AND W_ISCOMPLETED ='Y';
   
  O_DEBUG_POINT :='4W';
  
   INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT (P_ID, P_PANNUMBER, P_ORIGINAL_AMOUNT, P_CARD_ENTRYMODE, P_MERCHANTID, P_TERMINALID,
  P_INVOICENUMBER, P_TERMINAL_SERIAL_NUMBER, P_DATE, P_REFERENCE_VALUE, P_BATCH_NUMBER, P_REQUEST_TYPE, P_RESPONSE_CODE,  
  P_RETRIVAL_REF_NUMBER, P_STAN_NUMBER, P_CREATED, P_UPDATED, P_SETTLEMENT_FLAG, 
  P_PROCESSING_CODE, P_MTI, P_TXN_CHANNEL, P_APP_NAME, P_EXTRA_INFO,P_FIELD55,P_CARD_LABEL,P_REFUND_APPROVED,P_CURRENCY_CODE ) 
    SELECT SEQ_TC_WALLET_SETTLEMENT_ID.NEXTVAL, '405663' || W_WALLET_ID, W_TXN_AMOUNT, '010', W_MID, W_TID, W_INV_NUMBER, W_TERM_SER_NUM, W_TXN_DATENTIME,
 W_TXN_ID,W_BATCH_NUMBER, W_REQUEST_TYPE, SUBSTR(W_RESPONSE_CODE,4,2) , W_TXN_REF_ID, '000001', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,
 'Y', CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '000000' WHEN 'REFUND' THEN '200000' WHEN 'REVERSAL' THEN '000000' END,
 CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '200' WHEN 'REFUND' THEN '220' WHEN 'REVERSAL' THEN '400' END,'F',
 W_WALLET_TYPE, W_TXN_ID,W_RESPONSE_DESC,W_WALLET_TYPE,W_REFUND_APPROVED,'356' FROM TCH_WALLET_TXN WHERE (W_RESPONSE_CODE <> '00' OR W_REQUEST_TYPE = 'REVERSAL' );
       
        O_DEBUG_POINT :='5W';
        
         IF V_WALLET_PID.COUNT > 0 THEN
         O_DEBUG_POINT :='6W';
          FOR INDXX IN V_WALLET_PID.FIRST..V_WALLET_PID.LAST LOOP
            DELETE FROM TCH_WALLET_TXN WHERE W_TXN_REF_ID  = V_WALLET_PID(INDXX) 
            AND W_TID = V_WALLET_TID(INDXX);
          END LOOP; 
          O_DEBUG_POINT :='7W';
       END IF;
    END;
    
  END IF;

  
   EXCEPTION
  WHEN NO_DATA_FOUND THEN
    IF O_DEBUG_POINT = '2W' THEN
      O_APP_ERROR_CODE:='A-001';
    END IF;
  WHEN OTHERS THEN
    IF O_DEBUG_POINT = '2W' THEN
      O_APP_ERROR_CODE:='A-001';
    END IF;
  O_SQL_ERROR_CODE := SQLCODE;
  
  END TCH_AUTOSETTLEMENT_WALLET_PROC;