create or replace 
PROCEDURE TCH_PAYMENT_WALLET_PROC 
(
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2  
, O_MERCHANT_ID OUT VARCHAR2  
, O_TERMINAL_ID OUT VARCHAR2
, O_BATCH_NUMBER OUT VARCHAR2
, O_SQL_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
, O_DEBUG_POINT OUT VARCHAR2 
, O_TXN_COUNT OUT VARCHAR2
, O_DAILY_LIMIT OUT VARCHAR2
, O_SUMM_FLAG OUT VARCHAR2
, C_APP_CONFIG OUT SYS_REFCURSOR
) AS 

V_COUNT NUMBER(20):=NULL; 
BEGIN

    SELECT COUNT(1) INTO V_COUNT FROM TC_TID_HWSR_MAPPING 
    WHERE HWSRNO = I_TERMINAL_SERIAL_NUMBER AND STATUS = 'A' ;
  
    
    IF V_COUNT <> 1 THEN
        BEGIN
          O_DEBUG_POINT:='2B';
          RAISE_APPLICATION_ERROR(-20201, 'NO MAPPING FOUND IN INSIGHT DB');
        END;
   ELSE
      SELECT  DAILY_TXN_COUNT,MID,TID INTO O_DAILY_LIMIT,O_MERCHANT_ID,O_TERMINAL_ID FROM TC_TID_HWSR_MAPPING 
    WHERE HWSRNO = I_TERMINAL_SERIAL_NUMBER AND STATUS = 'A' ;
    O_DEBUG_POINT:='1A';
    
    O_BATCH_NUMBER:= GET_BATCH_NUMBER(I_TERMINAL_SERIAL_NUMBER,O_MERCHANT_ID,O_TERMINAL_ID);  
    
        OPEN C_APP_CONFIG FOR
      SELECT * FROM TCH_APPL_CONFIG;
    
    O_DEBUG_POINT:='1B';
    SELECT SUM(TOTAL_COUNT) INTO O_TXN_COUNT FROM 
    (
      SELECT COUNT(1) AS TOTAL_COUNT FROM TCH_PAYMENT_TXN 
      WHERE P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
      AND P_REQUEST_TYPE IN ('SALE','VOID','VOIDSALECSHBK','SALECSHBK','CSHBK')
      AND P_RESPONSE_CODE = '00'
       
      UNION ALL
      
      SELECT COUNT(1) AS TOTAL_COUNT FROM TCH_PAYMENT_AMEX_TXN 
        WHERE P_TERMINAL_SERIAL_NUMBER = I_TERMINAL_SERIAL_NUMBER
        AND P_REQUEST_TYPE IN ('SALE','VOID','VOIDSALECSHBK','SALECSHBK','CSHBK')
        AND P_RESPONSE_CODE = '00'
        
      UNION ALL
      
      SELECT COUNT(1) AS TOTAL_COUNT FROM TCH_WALLET_TXN 
        WHERE W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER 
        AND W_REQUEST_TYPE IN ('SALE','REFUND')
        AND W_RESPONSE_CODE = '00'
        AND  W_ISCOMPLETED ='Y'
      );
    
        O_DEBUG_POINT:='1C';
    -- TO SET SUMMARY REPORT FLAG AND SEND SAME TO EDC
    O_SUMM_FLAG := '0';
    O_TXN_COUNT := TO_NUMBER(O_TXN_COUNT + 1);
    IF TO_NUMBER(O_TXN_COUNT) = TO_NUMBER(O_DAILY_LIMIT) THEN
      O_DEBUG_POINT:='6AAB';
      O_SUMM_FLAG:='1';
    ELSIF  TO_NUMBER(O_TXN_COUNT) > TO_NUMBER(O_DAILY_LIMIT) THEN
      O_SUMM_FLAG:='2';
    END IF;
    
    O_DEBUG_POINT:='1D';
   END IF;
    
      EXCEPTION
      WHEN NO_DATA_FOUND THEN 
        IF O_DEBUG_POINT = '2B' THEN 
           O_APP_ERROR_CODE :=  'S-009';
        END IF;
      
      WHEN OTHERS THEN
   
        IF O_DEBUG_POINT = '2B' THEN
            O_APP_ERROR_CODE:='S-009';
        END IF ;      
        O_SQL_CODE := SQLCODE; 
    
END TCH_PAYMENT_WALLET_PROC;