CREATE TABLE "TCH"."TCH_USERROLES" 
   (	"USERID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLEID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_UR_COMP" PRIMARY KEY ("USERID", "ROLEID"), 
	 CONSTRAINT "FK_USERROLES_USERID" FOREIGN KEY ("USERID")
	  REFERENCES "TCH"."TCH_USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_USERROLES_ROLEID" FOREIGN KEY ("ROLEID")
	  REFERENCES "TCH"."TCH_ROLES" ("ID") ENABLE
   );