create or replace 
PROCEDURE TCH_SETTELEMENT_WALLET_PROC (
  I_TERMINAL_SERIAL_NUMBER IN VARCHAR2
, O_SQL_CODE OUT VARCHAR2
, O_APP_ERROR_CODE OUT VARCHAR2
, O_DEBUG_POINT OUT VARCHAR2
)AS 
TYPE TCH_STRING_ARRAY IS VARRAY (5000000) OF VARCHAR2(30);
V_WALLET_PID TCH_STRING_ARRAY;
V_WALLET_TID TCH_STRING_ARRAY;
V_COUNT NUMBER(4):=NULL;
V_MID VARCHAR2(20):=NULL;
V_TID VARCHAR2(15):=NULL;

  
CURSOR C_BATCH_TERM_LIST IS
  SELECT B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER FROM TCH_BATCH_SUMMARY GROUP BY B_BATCH_NUMBER,B_TERMINAL_SERIAL_NUMBER;
  
BEGIN

-- GET SETTLEMENT RELATED DATA
    O_DEBUG_POINT:='1';
    SELECT SUM(TOTAL_VAL) INTO V_COUNT FROM 
    (
      SELECT COUNT(1) AS TOTAL_VAL  FROM TCH_WALLET_TXN TTP
      WHERE TTP.W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER
        AND TTP.W_RESPONSE_CODE = '00' 
        AND TTP.W_REQUEST_TYPE <> 'REVERSAL' 
    );
    
    IF V_COUNT = 0 THEN
      O_DEBUG_POINT:='1A';
     
--  COPY REJECTED DATA FROM PAYMENT TABLE TO SETTLEMENT TABLE          
      INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT (P_ID, P_PANNUMBER, P_ORIGINAL_AMOUNT, P_CARD_ENTRYMODE, P_MERCHANTID, P_TERMINALID,
  P_INVOICENUMBER, P_TERMINAL_SERIAL_NUMBER, P_DATE, P_REFERENCE_VALUE, P_BATCH_NUMBER, P_REQUEST_TYPE, P_RESPONSE_CODE,  
  P_RETRIVAL_REF_NUMBER, P_STAN_NUMBER, P_CREATED, P_UPDATED, P_SETTLEMENT_FLAG, 
  P_PROCESSING_CODE, P_MTI, P_TXN_CHANNEL, P_APP_NAME, P_EXTRA_INFO,P_FIELD55,P_CARD_LABEL,P_REFUND_APPROVED,P_CURRENCY_CODE  ) 
    SELECT SEQ_TC_WALLET_SETTLEMENT_ID.NEXTVAL, '405663' || W_WALLET_ID, W_TXN_AMOUNT, '010', W_MID, W_TID, W_INV_NUMBER, W_TERM_SER_NUM, W_TXN_DATENTIME,
 W_TXN_ID,W_BATCH_NUMBER, W_REQUEST_TYPE, W_RESPONSE_CODE, W_TXN_REF_ID, '000001', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,
 'Y', CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '000000' WHEN 'REFUND' THEN '200000' WHEN 'REVERSAL' THEN '000000' END,
 CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '200' WHEN 'REFUND' THEN '220' WHEN 'REVERSAL' THEN '400' END,'F',
 W_WALLET_TYPE, W_TXN_ID,W_RESPONSE_DESC,W_WALLET_TYPE,W_REFUND_APPROVED,'356' FROM TCH_WALLET_TXN WHERE (W_RESPONSE_CODE <> '00' OR W_REQUEST_TYPE = 'REVERSAL' ) 
    AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER ;
              
      DELETE FROM TCH_WALLET_TXN  
        WHERE ( W_RESPONSE_CODE <> '00' 
          OR W_REQUEST_TYPE = 'REVERSAL' )
          AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER;
      RAISE_APPLICATION_ERROR(-20121,'NO DATA FOUND FOR SETTELEMENT');
    ELSE
     BEGIN
        O_DEBUG_POINT:='1B';
            SELECT W_TXN_REF_ID,W_TID BULK COLLECT INTO V_WALLET_PID,V_WALLET_TID FROM TCH_WALLET_TXN
        WHERE W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER;
        -- MOVE THE TRANSACTION FROM TCH PAYMENT TO TCH SETTLEMENT 
       INSERT INTO TCH_SETTLED_PAYMENT_TXN (P_ID, P_PANNUMBER, P_ORIGINAL_AMOUNT, P_CARD_ENTRYMODE, P_MERCHANTID, P_TERMINALID,
  P_INVOICENUMBER, P_TERMINAL_SERIAL_NUMBER, P_DATE, P_REFERENCE_VALUE, P_BATCH_NUMBER, P_REQUEST_TYPE, P_RESPONSE_CODE,  
  P_RETRIVAL_REF_NUMBER, P_STAN_NUMBER, P_CREATED, P_UPDATED, P_SETTLEMENT_FLAG, 
  P_PROCESSING_CODE, P_MTI, P_TXN_CHANNEL, P_APP_NAME, P_EXTRA_INFO,P_CARD_LABEL,P_REFUND_APPROVED,P_CURRENCY_CODE ) 
    SELECT SEQ_TC_WALLET_SETTLEMENT_ID.NEXTVAL, '405663' || W_WALLET_ID, W_TXN_AMOUNT, '010', W_MID, W_TID, W_INV_NUMBER, W_TERM_SER_NUM, W_TXN_DATENTIME,
 W_TXN_ID,  W_BATCH_NUMBER, W_REQUEST_TYPE, W_RESPONSE_CODE, W_TXN_REF_ID, '000001', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,
 'Y', CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '000000' WHEN 'REFUND' THEN '200000' END,
 CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '200' WHEN 'REFUND' THEN '220' END,'F',
 W_WALLET_TYPE, W_TXN_ID,W_WALLET_TYPE,W_REFUND_APPROVED,'356' FROM TCH_WALLET_TXN WHERE W_RESPONSE_CODE='00' AND (W_REQUEST_TYPE = 'SALE' OR W_REQUEST_TYPE='REFUND') 
        AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER AND W_ISCOMPLETED ='Y';       
        --END OF MOVE THE TRANSACTION FROM TCH PAYMENT TO TCH SETTLEMENT
        
 --COPY REJECTED DATA FROM PAYMENT TABLE TO SETTLEMENT TABLE  
     INSERT INTO TCH_SETTLED_PAYMENT_RT_VT_TT (P_ID, P_PANNUMBER, P_ORIGINAL_AMOUNT, P_CARD_ENTRYMODE, P_MERCHANTID, P_TERMINALID,
  P_INVOICENUMBER, P_TERMINAL_SERIAL_NUMBER, P_DATE, P_REFERENCE_VALUE, P_BATCH_NUMBER, P_REQUEST_TYPE, P_RESPONSE_CODE,  
  P_RETRIVAL_REF_NUMBER, P_STAN_NUMBER, P_CREATED, P_UPDATED, P_SETTLEMENT_FLAG, 
  P_PROCESSING_CODE, P_MTI, P_TXN_CHANNEL, P_APP_NAME, P_EXTRA_INFO,P_FIELD55,P_CARD_LABEL,P_REFUND_FLAG,P_CURRENCY_CODE ) 
    SELECT SEQ_TC_WALLET_SETTLEMENT_ID.NEXTVAL, '405663' || W_WALLET_ID, W_TXN_AMOUNT, '010', W_MID, W_TID, W_INV_NUMBER, W_TERM_SER_NUM, W_TXN_DATENTIME,
 W_TXN_ID,W_BATCH_NUMBER, W_REQUEST_TYPE, SUBSTR(W_RESPONSE_CODE,4,2) , W_TXN_REF_ID, '000001', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,
 'Y', CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '000000' WHEN 'REFUND' THEN '200000' WHEN 'REVERSAL' THEN '000000' END,
 CASE W_REQUEST_TYPE  WHEN 'SALE' THEN '200' WHEN 'REFUND' THEN '220' WHEN 'REVERSAL' THEN '400' END,'F',
 W_WALLET_TYPE, W_TXN_ID,W_RESPONSE_DESC,W_WALLET_TYPE,W_REFUND_APPROVED,'356' FROM TCH_WALLET_TXN WHERE (W_RESPONSE_CODE <> '00' OR W_REQUEST_TYPE = 'REVERSAL' )
    AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER;
              
        O_DEBUG_POINT :='1BC';

          FOR INDXX IN V_WALLET_PID.FIRST..V_WALLET_PID.LAST LOOP
            DELETE FROM TCH_WALLET_TXN WHERE W_TXN_REF_ID  = V_WALLET_PID(INDXX) 
            AND W_TID = V_WALLET_TID(INDXX)
             AND W_TERM_SER_NUM = I_TERMINAL_SERIAL_NUMBER;
          END LOOP; 
       
        
         FOR P IN C_BATCH_TERM_LIST LOOP
          UPDATE TCH_BATCH_SUMMARY SET B_CLOSE_DATE = CURRENT_TIMESTAMP 
          WHERE B_TERMINAL_SERIAL_NUMBER = P.B_TERMINAL_SERIAL_NUMBER 
          AND B_BATCH_NUMBER = P.B_BATCH_NUMBER
          AND B_CLOSE_DATE IS NULL;
         END LOOP;
         COMMIT;
      END;
     END IF; 
     
 
   EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        IF O_DEBUG_POINT = '1A' THEN 
            O_APP_ERROR_CODE := 'S-888';
        ELSIF O_DEBUG_POINT = '3AA' THEN 
            O_APP_ERROR_CODE := 'SH-88';
        END IF;
    WHEN OTHERS THEN
        IF O_DEBUG_POINT = '1A' THEN 
            O_APP_ERROR_CODE := 'S-888'; 
        ELSIF O_DEBUG_POINT = '3AA' THEN 
            O_APP_ERROR_CODE := 'SH-88';
        END IF;
        
      O_SQL_CODE := SQLCODE;
    
END TCH_SETTELEMENT_WALLET_PROC;