CREATE TABLE "TCH"."TCH_USERATTEMPTS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"ATTEMPTS" NUMBER(1,0) NOT NULL ENABLE, 
	"LASTMODIFIED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_USER_ATTEMPTS_ID" PRIMARY KEY ("ID")
   );