
  CREATE TABLE "TC_CAPKEY_PARAMETER" 
   (	"BANKCODE" NUMBER(6,0) NOT NULL ENABLE, 
	"SCHEME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EXPIRYDATE" DATE, 
	"RID" NUMBER(10,0), 
	"INDEX" CHAR(1 BYTE), 
	"EXPONENT" NUMBER(10,0), 
	"MODULAS" VARCHAR2(300 BYTE)
   );