--------------------------------------------------------
--  File created - Thursday-February-23-2017   
--------------------------------------------------------
DROP TABLE "TCH_HANDSHAKES";
--------------------------------------------------------
--  DDL for Table TCH_HANDSHAKES
--------------------------------------------------------

  CREATE TABLE "TCH_HANDSHAKES" 
   (	"H_ID" NUMBER(24,0), 
	"H_EDC_APP_VERSION" VARCHAR2(12 CHAR), 
	"H_PACKET_NUMBER" NUMBER(5,0), 
	"H_HANDSHAKE_VERSION" VARCHAR2(7 CHAR), 
	"H_BIN_VALUES" VARCHAR2(256 CHAR), 
	"H_TERMINAL_SERIAL_NUMBER" VARCHAR2(20 CHAR), 
	"H_TERMINAL_MODEL" VARCHAR2(3 CHAR), 
	"H_CLIENT_ID" VARCHAR2(20 CHAR), 
	"H_BANK_NAME" VARCHAR2(100 CHAR), 
	"H_MERCHANT_NAME" VARCHAR2(300 CHAR), 
	"H_MERCHANT_LOCATION" VARCHAR2(100 CHAR), 
	"H_LAST_FOUR_DIGIT_PROMPT_FLAG" CHAR(1 BYTE), 
	"H_DATE" VARCHAR2(8 CHAR), 
	"H_TIME" VARCHAR2(6 CHAR), 
	"H_FLAGS" VARCHAR2(100 CHAR), 
	"H_DESC_FLAG" CHAR(10 BYTE) DEFAULT 'N', 
	"H_SESSION_KEY" VARCHAR2(64 CHAR), 
	"H_LEGAL_NAME" VARCHAR2(300 CHAR), 
	"H_RESPONSE_CODE" VARCHAR2(3 CHAR), 
	"H_STRACE_NUMBER" VARCHAR2(6 CHAR), 
	"H_TID" VARCHAR2(8 CHAR), 
	"H_NII" VARCHAR2(3 CHAR), 
	"H_LINE_ENCRYPTION_FLAG" CHAR(1 BYTE), 
	"H_TPDU" VARCHAR2(10 CHAR), 
	"H_INSTALL_FLAG" CHAR(1 BYTE) DEFAULT 'N', 
	"H_CREATED" TIMESTAMP (6), 
	"H_UPDATED" TIMESTAMP (6), 
	"H_RTM_FLAG" NUMBER(1,0) DEFAULT 0, 
	"H_DWNLD_TM" VARCHAR2(3 BYTE) DEFAULT 4, 
	"H_CARD_ACQUIRING_ID" VARCHAR2(50 BYTE), 
	"H_SPECIFIC_TIME" VARCHAR2(6 BYTE)
   );
--------------------------------------------------------
--  DDL for Index SYS_C0017004
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0017004" ON "TCH_HANDSHAKES" ("H_ID") ;
--------------------------------------------------------
--  Constraints for Table TCH_HANDSHAKES
--------------------------------------------------------

  ALTER TABLE "TCH_HANDSHAKES" ADD PRIMARY KEY ("H_ID");
  ALTER TABLE "TCH_HANDSHAKES" MODIFY ("H_TERMINAL_SERIAL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "TCH_HANDSHAKES" MODIFY ("H_ID" NOT NULL ENABLE);
  
  CREATE INDEX IDX_TCH_HANDSHAKES ON TCH_HANDSHAKES
  (
    H_TERMINAL_SERIAL_NUMBER
  );
  
  CREATE INDEX IDX_TCH_HANDSHAKES ON TCH_HANDSHAKES
  (
    H_TID
  );
  CREATE INDEX IDX_TCH_HANDSHAKES ON TCH_HANDSHAKES
  (
    H_CARD_ACQUIRING_ID
  );
  

