package com.awl.tch.brandemi.util;

public interface QueryConstant {
	
	public String PRODUCT_DETAILS = "SELECT T3.PRODUCTCODE , T3.PRODUCTDESCRIPTION ,  T1.PROGRAMCODE , T0.PROGRAMSHORTNAME, T3.NOEMICASHBACK, T3.PER_FIX , T3.AMOUNT  FROM  XP_EMI_PROGRAMMASTER T0 "
			+ "JOIN XP_EMI_PROGRAM_MERCHANT  T1 ON T0.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_PROGRAM_PRODUCT T2 ON T1.PROGRAMCODE = T2.PROGRAMCODE "
			+ "JOIN XP_EMI_PRODUCT T3 ON T3.PRODUCTCODE = T2.PRODUCTCODE "
			+ "JOIN XP_EMI_MID_DEALERSCHEME_MAP T4 ON T1.MERCHANTCODE = T4.MID "
			+ "JOIN XP_EMI_PROGRAM_SCHEME_MAPPING T5 ON T5.MID_DEALERSCHEMEID = T4.MID_DEALERSCHEMEID AND T5.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_MID_DLR_MAPPING T6 ON T6.MID_DLR_MAP_ID = T4.MID_DLR_MAP_ID AND T4.MANUFACTURERID = T3.PRODUCTMANUFACTURERID "
			+ "WHERE T1.MERCHANTCODE = ? AND  T3.STATUS = 'A' AND T1.STATUS = 'A' AND T3.PRODUCTMANUFACTURERID = ? AND  T4.SCHEMEID = ? AND T3.CHILDID  = ?";
	
	public String GET_SKU_WITH_MAN_CHK_old = "SELECT distinct * FROM (SELECT T3.PRODUCTCODE , T3.PRODUCTDESCRIPTION ,  T1.PROGRAMCODE , T0.PROGRAMSHORTNAME, "
			+ "T3.NOEMICASHBACK, T3.PER_FIX , T3.AMOUNT, T2.MANUFACTURERCODE  FROM  XP_EMI_PROGRAMMASTER T0 "
			+ "JOIN XP_EMI_PROGRAM_MERCHANT  T1 ON T0.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_PROGRAM_PRODUCT T2 ON T1.PROGRAMCODE = T2.PROGRAMCODE "
			+ "JOIN XP_EMI_PRODUCT T3 ON T3.PRODUCTCODE = T2.PRODUCTCODE "
			+ "JOIN XP_EMI_MID_DEALERSCHEME_MAP T4 ON T1.MERCHANTCODE = T4.MID "
			+ "JOIN XP_EMI_PROGRAM_SCHEME_MAPPING T5 ON T5.MID_DEALERSCHEMEID = T4.MID_DEALERSCHEMEID AND T5.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_MID_DLR_MAPPING T6 ON T6.MID_DLR_MAP_ID = T4.MID_DLR_MAP_ID AND T4.MANUFACTURERID = T3.PRODUCTMANUFACTURERID "
			+ "JOIN XP_EMI_PROGRAM_BIN T12 on T12.PROGRAMCODE=T0.PROGRAMCODE "
			+ "WHERE T1.MERCHANTCODE = ? AND  T3.STATUS = 'A' AND T1.STATUS = 'A' "
			+ "AND T3.PRODUCTMANUFACTURERID = ? AND  T4.SCHEMEID = ? AND T12.STATUS = 'A' and T12.BINCODE = ? AND T3.CHILDID  = ?) T7 "
			+ "JOIN XP_EMI_MANUFACTURER T8 ON T8.MANUFACTURERCODE = T7.MANUFACTURERCODE AND T8.MANUFACTURERNAME = ?";
	
	
	public String GET_SKU_WITH_MAN_CHK = "SELECT distinct * FROM (SELECT T3.PRODUCTCODE , "
			+ " T2.MANUFACTURERCODE  FROM  XP_EMI_PROGRAMMASTER T0 "
			+ "JOIN XP_EMI_PROGRAM_MERCHANT  T1 ON T0.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_PROGRAM_PRODUCT T2 ON T1.PROGRAMCODE = T2.PROGRAMCODE "
			+ "JOIN XP_EMI_PRODUCT T3 ON T3.PRODUCTCODE = T2.PRODUCTCODE "
			+ "JOIN XP_EMI_MID_DEALERSCHEME_MAP T4 ON T1.MERCHANTCODE = T4.MID "
			+ "JOIN XP_EMI_PROGRAM_SCHEME_MAPPING T5 ON T5.MID_DEALERSCHEMEID = T4.MID_DEALERSCHEMEID AND T5.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_MID_DLR_MAPPING T6 ON T6.MID_DLR_MAP_ID = T4.MID_DLR_MAP_ID AND T4.MANUFACTURERID = T3.PRODUCTMANUFACTURERID "
			+ "JOIN XP_EMI_PROGRAM_BIN T12 on T12.PROGRAMCODE=T0.PROGRAMCODE "
			+ "WHERE T1.MERCHANTCODE = ? AND  T3.STATUS = 'A' AND T1.STATUS = 'A' "
			+ "AND T3.PRODUCTMANUFACTURERID = ? AND  T4.SCHEMEID = ? AND T12.STATUS = 'A' and T12.BINCODE = ? AND T3.CHILDID  = ?) T7 "
			+ "JOIN XP_EMI_MANUFACTURER T8 ON T8.MANUFACTURERCODE = T7.MANUFACTURERCODE AND T8.MANUFACTURERNAME = ?";
	
	public String GET_SKU_WITH_MAN_CHK_BIN_CHK_REMOVED = "SELECT distinct * FROM (SELECT T3.PRODUCTCODE , "
			+ " T2.MANUFACTURERCODE  FROM  XP_EMI_PROGRAMMASTER T0 "
			+ "JOIN XP_EMI_PROGRAM_MERCHANT  T1 ON T0.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_PROGRAM_PRODUCT T2 ON T1.PROGRAMCODE = T2.PROGRAMCODE "
			+ "JOIN XP_EMI_PRODUCT T3 ON T3.PRODUCTCODE = T2.PRODUCTCODE "
			+ "JOIN XP_EMI_MID_DEALERSCHEME_MAP T4 ON T1.MERCHANTCODE = T4.MID "
			+ "JOIN XP_EMI_PROGRAM_SCHEME_MAPPING T5 ON T5.MID_DEALERSCHEMEID = T4.MID_DEALERSCHEMEID AND T5.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_MID_DLR_MAPPING T6 ON T6.MID_DLR_MAP_ID = T4.MID_DLR_MAP_ID AND T4.MANUFACTURERID = T3.PRODUCTMANUFACTURERID "
			+ "WHERE T1.MERCHANTCODE = ? AND  T3.STATUS = 'A' AND T1.STATUS = 'A' "
			+ "AND T3.PRODUCTMANUFACTURERID = ? AND  T4.SCHEMEID = ? AND T3.CHILDID  = ?) T7 "
			+ "JOIN XP_EMI_MANUFACTURER T8 ON T8.MANUFACTURERCODE = T7.MANUFACTURERCODE AND T8.MANUFACTURERNAME = ?";
	
	
	
	public String PRODUCT_DETAILS_WITH_SKU_MANF_old = "SELECT * FROM (SELECT T3.PRODUCTCODE , T3.PRODUCTDESCRIPTION ,  T1.PROGRAMCODE , T0.PROGRAMSHORTNAME, "
			+ "T3.NOEMICASHBACK, T3.PER_FIX , T3.AMOUNT, T2.MANUFACTURERCODE  FROM  XP_EMI_PROGRAMMASTER T0 "
			+ "JOIN XP_EMI_PROGRAM_MERCHANT  T1 ON T0.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_PROGRAM_PRODUCT T2 ON T1.PROGRAMCODE = T2.PROGRAMCODE "
			+ "JOIN XP_EMI_PRODUCT T3 ON T3.PRODUCTCODE = T2.PRODUCTCODE "
			+ "JOIN XP_EMI_MID_DEALERSCHEME_MAP T4 ON T1.MERCHANTCODE = T4.MID "
			+ "JOIN XP_EMI_PROGRAM_SCHEME_MAPPING T5 ON T5.MID_DEALERSCHEMEID = T4.MID_DEALERSCHEMEID AND T5.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_MID_DLR_MAPPING T6 ON T6.MID_DLR_MAP_ID = T4.MID_DLR_MAP_ID AND T4.MANUFACTURERID = T3.PRODUCTMANUFACTURERID "
			+ "WHERE T1.MERCHANTCODE = ? AND  T3.STATUS = 'A' AND T1.STATUS = 'A' AND T3.PRODUCTCODE = ? "
			+ "AND T3.PRODUCTMANUFACTURERID = ? AND  T4.SCHEMEID = ? AND T3.CHILDID  = ?) T7 "
			+ "JOIN XP_EMI_MANUFACTURER T8 ON T8.MANUFACTURERCODE = T7.MANUFACTURERCODE AND T8.MANUFACTURERNAME = ?";
	
	public String PRODUCT_DETAILS_WITH_SKU_MANF = "SELECT distinct * FROM (SELECT T3.PRODUCTCODE , T3.PRODUCTDESCRIPTION , T1.PROGRAMCODE ,  T0.PROGRAMSHORTNAME, "
			+ "T3.NOEMICASHBACK, T3.PER_FIX , T3.AMOUNT, T2.MANUFACTURERCODE  FROM  XP_EMI_PROGRAMMASTER T0 "
			+ "JOIN XP_EMI_PROGRAM_MERCHANT  T1 ON T0.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_PROGRAM_PRODUCT T2 ON T1.PROGRAMCODE = T2.PROGRAMCODE "
			+ "JOIN XP_EMI_PRODUCT T3 ON T3.PRODUCTCODE = T2.PRODUCTCODE "
			+ "JOIN XP_EMI_MID_DEALERSCHEME_MAP T4 ON T1.MERCHANTCODE = T4.MID "
			+ "JOIN XP_EMI_PROGRAM_SCHEME_MAPPING T5 ON T5.MID_DEALERSCHEMEID = T4.MID_DEALERSCHEMEID AND T5.PROGRAMCODE = T1.PROGRAMCODE "
			+ "JOIN XP_EMI_MID_DLR_MAPPING T6 ON T6.MID_DLR_MAP_ID = T4.MID_DLR_MAP_ID AND T4.MANUFACTURERID = T3.PRODUCTMANUFACTURERID "
			+ "JOIN XP_EMI_PROGRAM_BIN T12 on T12.PROGRAMCODE=T0.PROGRAMCODE "
			+ "WHERE T1.MERCHANTCODE = ? AND  T3.STATUS = 'A' AND T1.STATUS = 'A' AND T3.PRODUCTCODE = ? "
			+ "AND T3.PRODUCTMANUFACTURERID = ? AND  T4.SCHEMEID = ? AND T12.STATUS = 'A' and T12.BINCODE = ?  AND T3.CHILDID  = ?) T7 "
			+ "JOIN XP_EMI_MANUFACTURER T8 ON T8.MANUFACTURERCODE = T7.MANUFACTURERCODE AND T8.MANUFACTURERNAME = ?";
	
	
	public String VALIDATION_QUERY = "SELECT IS_VALIDATION , NO_OF_DAYS , VELCOUNT , VELOCITY_NOOFDAYS , VELOCITYCHECK , VELOCITY FROM XP_EMI_MID_DEALERSCHEME_MAP  WHERE "
			+ "MID=? AND CATEGORYID = ? AND MANUFACTURERID = ? AND SCHEMEID = ?";

	public String DEALERCODE_QUERY = "SELECT DEALER_CODE FROM XP_EMI_MID_DLR_MAPPING WHERE MID = ? AND MANUFACT_ID = ?";

	public String MANUFACTURER_DETAILS = "SELECT T1.MANUFACTURERCODE , T1.MANUFACTURERNAME, T1.MANUFACTURERDESCLAIMER FROM XP_EMI_MANUFACTURER T1 "
				+ "WHERE T1.MANUFACTURERID IN (SELECT DISTINCT T2.MANUFACTURERID FROM XP_EMI_MID_DEALERSCHEME_MAP T2 WHERE T2.MID = ? AND T2.MANUFACTURERID = ?)";

	public String MENU_HIERARCHY = "SELECT  T3.ID , CASE WHEN T2.PARENT_KEYS IS NULL THEN 0 ELSE T2.PARENT_KEYS END PREVIOUS_ID  , T2.ID AS  CURRENT_ID , T2.NAME , T2.DESCRIPTION  "
			+ " FROM XP_EMI_PRODUCT_HIERARCHY T2 RIGHT OUTER JOIN (SELECT  CASE WHEN connect_by_root(T1.PARENT_KEYS) IS NULL THEN T1.ID "
			+ "ELSE connect_by_root(T1.PARENT_KEYS)  END HID, T1.ID  FROM XP_EMI_PRODUCT_HIERARCHY T1  "
			+ "   WHERE T1.ID IN ( :ids )   CONNECT BY PRIOR T1.ID = T1.PARENT_KEYS) T3 ON T3.HID = T2.ID WHERE T2.ID IS NOT NULL ORDER BY 1";

	String GET_MID = "SELECT DISTINCT MID FROM XP_EMI_MID_DLR_MAPPING";
	
	String GET_MID_MAN_SCHEME = "SELECT T2.MANUFACTURERID,T2.categoryid FROM XP_EMI_MID_DEALERSCHEME_MAP T2 WHERE T2.MID in (:mid) AND T2.STATUS = 'A'";
	
	String GET_BIN_MID_MAPPING = "select distinct BINCODE from XP_EMI_PROGRAM_BIN t1 join XP_EMI_PROGRAM_MERCHANT"
			+ " t2 on t1.programcode = t2.programcode where t2.merchantcode = ? AND t1.status = 'A' AND T2.status = 'A'";
}
