 CREATE TABLE "TCH"."TCH_FUNCTIONS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FUNCTIONNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"URL" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"GROUPID" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP ENABLE,  
	 CONSTRAINT "PK_FUNCTIONS_ID" PRIMARY KEY ("ID"), 
	 CONSTRAINT "FK_FUN_GROUPID" FOREIGN KEY ("GROUPID")
	  REFERENCES "TCH"."TCH_FUNCTIONGROUPS" ("ID") ENABLE
   );