
package com.awl.tch.brandemi.samsung;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateSerialServiceSoap", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateSerialServiceSoap {


    /**
     * 
     * @param salesType
     * @param serialNumber
     * @param ceAuthHeader
     * @param partnerCode
     * @param vendor
     * @param saleDate
     * @param referenceID
     * @param skuCode
     * @param productType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CESerialSaleConfirmation", action = "http://107.108.6.139/EMIHHPPineLabUAT/CESerialSaleConfirmation")
    @WebResult(name = "CESerialSaleConfirmationResult", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
    @RequestWrapper(localName = "CESerialSaleConfirmation", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.CESerialSaleConfirmation")
    @ResponseWrapper(localName = "CESerialSaleConfirmationResponse", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.CESerialSaleConfirmationResponse")
    public String ceSerialSaleConfirmation(
        @WebParam(name = "ReferenceID", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String referenceID,
        @WebParam(name = "SerialNumber", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String serialNumber,
        @WebParam(name = "SaleDate", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String saleDate,
        @WebParam(name = "SKUCode", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String skuCode,
        @WebParam(name = "Vendor", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String vendor,
        @WebParam(name = "SalesType", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String salesType,
        @WebParam(name = "ProductType", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String productType,
        @WebParam(name = "PartnerCode", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String partnerCode,
        @WebParam(name = "CEAuthHeader", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", header = true, partName = "CEAuthHeader")
        CEAuthHeader ceAuthHeader);

    /**
     * 
     * @param salesType
     * @param serialNumber
     * @param ceAuthHeader
     * @param partnerCode
     * @param vendor
     * @param saleDate
     * @param referenceID
     * @param skuCode
     * @param productType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CESerialSaleValidate", action = "http://107.108.6.139/EMIHHPPineLabUAT/CESerialSaleValidate")
    @WebResult(name = "CESerialSaleValidateResult", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
    @RequestWrapper(localName = "CESerialSaleValidate", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.CESerialSaleValidate")
    @ResponseWrapper(localName = "CESerialSaleValidateResponse", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.CESerialSaleValidateResponse")
    public String ceSerialSaleValidate(
        @WebParam(name = "ReferenceID", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String referenceID,
        @WebParam(name = "SerialNumber", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String serialNumber,
        @WebParam(name = "SaleDate", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String saleDate,
        @WebParam(name = "SKUCode", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String skuCode,
        @WebParam(name = "Vendor", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String vendor,
        @WebParam(name = "SalesType", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String salesType,
        @WebParam(name = "ProductType", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String productType,
        @WebParam(name = "PartnerCode", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String partnerCode,
        @WebParam(name = "CEAuthHeader", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", header = true, partName = "CEAuthHeader")
        CEAuthHeader ceAuthHeader);

    /**
     * 
     * @param serialNumber
     * @param ceAuthHeader
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UnblockSerialService", action = "http://107.108.6.139/EMIHHPPineLabUAT/UnblockSerialService")
    @WebResult(name = "UnblockSerialServiceResult", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
    @RequestWrapper(localName = "UnblockSerialService", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.UnblockSerialService")
    @ResponseWrapper(localName = "UnblockSerialServiceResponse", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.UnblockSerialServiceResponse")
    public String unblockSerialService(
        @WebParam(name = "SerialNumber", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String serialNumber,
        @WebParam(name = "CEAuthHeader", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", header = true, partName = "CEAuthHeader")
        CEAuthHeader ceAuthHeader);

    /**
     * 
     * @param oldPassword
     * @param newPassword
     * @param confirmPassword
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CESerialChangePassword", action = "http://107.108.6.139/EMIHHPPineLabUAT/CESerialChangePassword")
    @WebResult(name = "CESerialChangePasswordResult", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
    @RequestWrapper(localName = "CESerialChangePassword", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.CESerialChangePassword")
    @ResponseWrapper(localName = "CESerialChangePasswordResponse", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/", className = "com.awl.tch.brandemi.samsung.CESerialChangePasswordResponse")
    public String ceSerialChangePassword(
        @WebParam(name = "UserName", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String userName,
        @WebParam(name = "OldPassword", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String oldPassword,
        @WebParam(name = "NewPassword", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String newPassword,
        @WebParam(name = "ConfirmPassword", targetNamespace = "http://107.108.6.139/EMIHHPPineLabUAT/")
        String confirmPassword);

}
